<center>
<img src="https://drive.google.com/uc?id=1f1gGVI-rxcHjA90WEGNvvtSXF1pAxQwg" alt="Fasilkom UI" width="300"/>

CSGE603130 • Kecerdasan Artifisial dan Sains Data Dasar

Semester Genap 2024/2025

Fakultas Ilmu Komputer, Universitas Indonesia

##**Lab 1: *Pengenalan Pandas dan NumPy***

###**Tenggat Waktu: 09 Februari 2025 23.55 WIB**
</center>

### **Ketentuan:**

1. Dokumen template lab dengan format .ipynb dan dataset (jika dibutuhkan) telah disediakan di SCeLe
2. Jalankan kode pada dokumen .ipynb dan perhatikan dengan saksama apa yang potongan kode tersebut lakukan beserta dengan keluarannya. Jawablah **pertanyaan** yang disisipkan pada potongan program yang diberikan.
3. Dokumen Jupyter Notebook yang telah dilengkapi dengan jawaban dikumpulkan dengan format penamaan **Kelas_LabX_NPM_Nama.ipynb** . Contoh: A_Lab1_1806205773_Abdurrafi Arief.ipynb. Kesalahan dalam pengumpulan nama akan dikenakan pinalti sebesar 5 poin.
4. Kumpulkan dokumen tersebut pada submisi yang telah disediakan di SCeLe sesuai dengan kelas masing-masing sebelum **Tenggat Waktu: 09 Februari 2025, 23.55 WIB**.
5. Keterlambatan pengumpulan akan dikenakan pinalti sebesar 5 poin per jam (pembulatan ke atas). Dengan cut off 1 hari.
6. Lab ini dirancang sebagai **tugas mandiri**. Plagiarisme tidak diperkenankan dalam bentuk apapun. Adapun kolaborasi berupa diskusi (tanpa menyalin maupun mengambil jawaban orang lain) dan literasi masih diperbolehkan dengan mencantumkan kolaborator dan sumber.
7. Pakta Integritas **Wajib** di isi dan di jalankan. Submisi hanya akan dinilai jika pakta integritas di isi dan di jalankan.
8. Sebelum di kumpulkan, kode **WAJIB** dijalankan. Jika tidak, dikenakan penalti sebesar 50%.
9. Mahasiswa wajib mencantumkan semua sumber yang menjadi referensi jawaban, termasuk GPT.



In [22]:
# Isi dengan data diri Anda
NAMA = "Yoshelin Yamala Vijnana"
KELAS = "C"
NPM = "2206826702"
USERNAME_KAGGLE = "yoshelinyamala"

# Isi dengan NPM teman yang berdiskusi dengan Anda
KOLABORATOR = []

# Isi dengan sumber referensi yang Anda gunakan dalam mengerjakan
REFERENSI = ["ChatGPT", "Google", "StackOverflow"]

In [155]:
PERNYATAAN_INTEGRITAS = "Saya, %s dari kelas %s dengan NPM %s, menyatakan bahwa seluruh jawaban pada pekerjaan ini murni saya kerjakan sendiri.\n\
Saya tidak mencontek jawaban, memberikan jawaban, maupun menyalin dari sumber manapun.\n \
\n\
Jika saya melanggar pernyataan tersebut, saya siap menerima konsekuensi apapun yang diberikan.\n   \
(%s)" % (NAMA, KELAS, NPM, NAMA)

print(PERNYATAAN_INTEGRITAS)

Saya, Yoshelin Yamala Vijnana dari kelas C dengan NPM 2206826702, menyatakan bahwa seluruh jawaban pada pekerjaan ini murni saya kerjakan sendiri.
Saya tidak mencontek jawaban, memberikan jawaban, maupun menyalin dari sumber manapun.
 
Jika saya melanggar pernyataan tersebut, saya siap menerima konsekuensi apapun yang diberikan.
   (Yoshelin Yamala Vijnana)


# Penguatan Python

Python merupakan bahasa pemrograman yang akan digunakan pada tutorial mata kuliah ini. Terdapat playlist YouTube [Python DDP 1](https://www.youtube.com/playlist?list=PLvkbIcjwo0qwModeUU2JyUi2RQcI6Nfc-) yang telah disediakan oleh Pak Fariz untuk mendukung dan membantu pemahaman kalian dalam Python. Semoga sukses dalam belajarmu, Semangat ya!

# **1. Pengantar Jupyter Notebook**

Berkas yang akan digunakan pada tutorial yaitu berkas IPYNB. Berkas IPYNB dapat dibentuk dan dibuka menggunakan aplikasi daring seperti [Google Colab](https://www.kaggle.com/notebooks) atau [Kaggle](https://www.kaggle.com/notebooks), ataupun Jupyter Notebook. Dalam berkas ini, konten disusun dalam bentuk sel (cells), yang terdiri dari tiga jenis utama, diantaranya yaitu code cells untuk menulis dan menjalankan kode, markdown cells untuk menulis teks deskriptif atau dokumentasi, serta raw cells untuk menyimpan teks mentah.

Setiap cell dapat dieksekusi dengan kombinasi shortcut **shift + enter** ataupun **tombol run** pada tiap cell. Setiap cell dapat dieksekusi secara mandiri dan tidak perlu dijalankan berurutan, kecuali jika ada variabel global yang diinisiasi pada cell yang belum dijalankan. Cell kode Python yang dieksekusi akan menjalankan kode secara *interpreted* dan menampilkan output (jika ada) di bawah cell.

In [156]:
# Berikut merupakan contoh cell untuk kode Python
# Cell dapat digunakan untuk mengeksekusi kode yang diperlukan

var = "Hello, world!"
print(var[:])
var

Hello, world!


'Hello, world!'

## Contoh cell untuk *text markdown*

Ini adalah contoh cell untuk text markdown.

Markdown adalah bahasa markup yang digunakan untuk membuat teks berformat menggunakan editor teks sederhana. Dengan Markdown, dapat dibuat berbagai format teks seperti *heading*, tautan, tabel, daftar, dan banyak lagi. Beragam sintaks Markdown dapat ditemukan dalam [panduan di Markdownguide.org](https://www.markdownguide.org/cheat-sheet/) serta [dokumentasi wiki](https://github.com/adam-p/markdown-here/wiki/Markdown-Here-Cheatsheet) yang dibuat oleh Adam Pritchard.

## 1.1 Instalasi library pada Jupyter Notebook

Secara umum, *tools* seperti JupyterLab dan Google Colab telah menyediakan kernel yang dilengkapi dengan beberapa *library* Python. Namun, untuk menginstal library tambahan yang dibutuhkan, dapat dijalankan perintah `pip install nama-package` pada cell kode. Sebagai contoh, berikut adalah cell untuk menginstall library **Pandas**.



In [157]:
!pip install pandas


[notice] A new release of pip is available: 24.3.1 -> 25.0
[notice] To update, run: python.exe -m pip install --upgrade pip


Kernel yang digunakan di Jupyter Notebook, seperti halnya kernel pada umumnya, dapat menerima perintah sistem. Selain perintah seperti `pip`, berbagai perintah lain, seperti `git` atau `apt`, juga dapat dijalankan asalkan kernel yang digunakan mendukungnya. Silahkan  mengeksplorasi lebih lanjut penggunaannya, baik pada perangkat lokal seperti Jupyter Notebook maupun platform berbasis *cloud* seperti Google Colab.

# **2. Pengenalan Pandas**

Pandas merupakan alat analisis dan manipulasi data sumber terbuka yang cepat, kuat, fleksibel, dan mudah digunakan, dibangun di atas bahasa pemrograman Python (Pandas - Python Data Analysis Library, n.d.). Terdapat pula [dokumentasi Pandas](https://pandas.pydata.org/docs/getting_started/index.html) sebagai acuan dalam berlatih menggunakan library ini.

In [158]:
# import library
import pandas as pd

Terdapat struktur data utama yang digunakan di Pandas, yaitu Series dan DataFrame. Series merupakan struktur data satu dimensi seperti array atau daftar Python, yang memiliki indeks unik untuk setiap elemen. Umumnya, series cocok digunakan untuk menangani data seperti kolom tunggal dari tabel. Sedangkan, DataFrame merupakan struktur data dua dimensi yang menyerupai tabel dengan baris dan kolom. DataFrame sangat fleksibel karena setiap kolom dapat memiliki tipe data yang berbeda.
Berikut penjelasan dan contoh detail dari Series maupun DataFrame.

## 2.1 Series

Series adalah struktur data satu dimensi yang serupa dengan array. Series memiliki indeks dan nilai (*value*), di mana indeks secara default berupa angka dari 0 hingga N-1, dengan N merupakan panjang Series. Series dapat dibuat menggunakan berbagai tipe data, seperti *list*, *tuple*, atau *dictionary*.

Salah satu cara yang umum digunakan untuk membuat objek Series adalah sebagai berikut.

```
pd.Series(data)
```

`data` di atas dapat berupa *list*, *tuple*, atau *dictionary*.

Berikut merupakan contoh penggunaan Series.

In [159]:
# Membuat objek Series dari sebuah list
series = pd.Series([1,2,4,8,16,32])
series

0     1
1     2
2     4
3     8
4    16
5    32
dtype: int64

Berdasarkan kode di atas, Series menunjukkan tipe data yang diberikan dengan contoh tersebut adalah integer. Selain itu, Series memiliki *index* yang terletak di bagian sebelah kiri dan *value* yang terletak di bagian sebelah kanan. Kedua hal tersebut dapat diakses dengan menggunakan atribut `index` dan `values`.  Untuk melihat lebih detail terkait *index* dan *value* nya, dapat menggunakan kode sebagai berikut.

In [160]:
# Melihat index dari series
series.index

RangeIndex(start=0, stop=6, step=1)

In [161]:
# Melihat values dari series
series.values

array([ 1,  2,  4,  8, 16, 32])

Tidak hanya itu, Series juga dapat diakses menggunakan teknik *indexing* dan *slicing* dengan contoh sebagai berikut.

In [162]:
# Melakukan indexing pada series
series[1]

np.int64(2)

In [163]:
# Melakukan slicing pada series
series[1:4]

1    2
2    4
3    8
dtype: int64

Pada contoh di atas, *indexing* digunakan untuk untuk mengakses elemen individual berdasarkan indeks atau label. Sedangkan, *slicing* digunakan untuk memilih subset dari data berdasarkan rentang *index*. Slicing dapat dilakukan dengan menggunakan index atau label dan akan mengembalikan elemen dalam rentang yang ditentukan.

## 2.2 DataFrame

DataFrame adalah struktur data dua dimensi yang mirip dengan tabel. DataFrame memiliki indeks dan kolom. Secara default, indeks pada DataFrame berupa angka yang dimulai dari 0 hingga N-1, di mana N adalah jumlah baris pada DataFrame. DataFrame dapat dibuat menggunakan berbagai tipe data seperti *list*, *tuple*, *dictionary*, dan Series. Setiap kolom dalam DataFrame dapat memiliki tipe data yang berbeda, seperti *integer*, *string*, atau *float*. Seperti halnya Series, DataFrame juga memiliki indeks yang unik untuk setiap barisnya.

<br>DataFrame dapat digunakan untuk menyimpan dan memanipulasi data yang berasal dari berbagai sumber, seperti file CSV, Excel, atau basis data SQL. Salah satu cara umum untuk membuat objek DataFrame adalah dengan menggunakan sintaks berikut.

```
pd.DataFrame(data, columns=column_names)
```

`data` di atas dapat berupa list, tuple, atau dictionary.

`column_names` adalah list yang berisi nama kolom.

Berikut merupakan contoh penggunaan DataFrame.


### 2.2.1 Pembuatan DataFrame

#### 1. Pembuatan DataFrame melalui List

In [164]:
# Memasukkan data ke dalam lists
data_list = [
    [1, 'Jane', 80],
    [2, 'John', 90],
    [3, 'Doe', 70]
]

# Membuat dataframe
df_list = pd.DataFrame(data_list, columns=['ID', 'Name', 'Score'])
df_list

ID  Name  Score
0   1  Jane     80
1   2  John     90
2   3   Doe     70

#### 2. Pembuatan DataFrame melalui Dictionary

 * Pembuatan DataFrame melalui *Dictionary of Lists*

In [165]:
# Memasukkan data ke dalam dictionary of lists
data_dict = {
    'ID': [1, 2, 3],
    'Name': ['Jane', 'John', 'Doe'],
    'Score': [80, 90, 70]
}

# Membuat dataframe
df_dict = pd.DataFrame(data_dict)
df_dict

ID  Name  Score
0   1  Jane     80
1   2  John     90
2   3   Doe     70

* Pembuatan DataFrame melalui *Dictionary of Series*

In [166]:
# Memasukkan data ke dalam dictionary of series
data_series = {
    'ID': pd.Series([1, 2, 3]),
    'Name': pd.Series(['Jane', 'John', 'Doe']),
    'Score': pd.Series([80, 90, 70])
}

# Membuat dataframe
df_series = pd.DataFrame(data_series)
df_series

ID  Name  Score
0   1  Jane     80
1   2  John     90
2   3   Doe     70

#### 3. Pembuatan DataFrame melalui Tuple

In [167]:
# Memasukkan data ke dalam
data_tuple = [
    (1, 'Jane', 80),
    (2, 'John', 90),
    (3, 'Doe', 70)
]

# Membuat dataframe
df_tuple = pd.DataFrame(data_tuple, columns=['ID', 'Name', 'Score'])
df_tuple

ID  Name  Score
0   1  Jane     80
1   2  John     90
2   3   Doe     70

#### 4. Pembuatan DataFrame melalui Series

In [168]:
# Memasukkan data ke dalam series
id_series = pd.Series([1, 2, 3], name='ID')
name_series = pd.Series(['Jane', 'John', 'Doe'], name='Name')
score_series = pd.Series([80, 90, 70], name='Score')

# Membuat dataframe
df_ser = pd.concat([id_series, name_series, score_series], axis=1)
df_ser

ID  Name  Score
0   1  Jane     80
1   2  John     90
2   3   Doe     70

#### 5. Pembuatan DataFrame melalui Sumber Eksternal

* Pembuatan DataFrame melalui Sumber Eksternal (URL Remote)

**Membaca berkas CSV dari URL remote**

In [169]:
# Membaca file CSV
df_remote = pd.read_csv(
    'https://archive.ics.uci.edu/ml/machine-learning-databases/zoo/zoo.data', # Path menuju berkas dataset, dapat berupa path lokal maupun URL remote
    header=None # Baris pertama dataset bukan header
)

display(df_remote) # Menampilkan DataFrame

0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  17
0    aardvark   1   0   0   1   0   0   1   1   1   1   0   0   4   0   0   1   1
1    antelope   1   0   0   1   0   0   0   1   1   1   0   0   4   1   0   1   1
2        bass   0   0   1   0   0   1   1   1   1   0   0   1   0   1   0   0   4
3        bear   1   0   0   1   0   0   1   1   1   1   0   0   4   0   0   1   1
4        boar   1   0   0   1   0   0   1   1   1   1   0   0   4   1   0   1   1
..        ...  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..
96    wallaby   1   0   0   1   0   0   0   1   1   1   0   0   2   1   0   1   1
97       wasp   1   0   1   0   1   0   0   0   0   1   1   0   6   0   0   0   6
98       wolf   1   0   0   1   0   0   1   1   1   1   0   0   4   1   0   1   1
99       worm   0   0   1   0   0   0   0   0   0   1   0   0   0   0   0   0   7
100      wren   0   1   1   0   1   0   0   0   1   1   0   0   2   1   0   0   2

[101 rows x 18 columns]

**Memberikan nama kolom pada DataFrame yang telah dibuat agar lebih bermakna**

In [170]:
df_remote.columns = [
    'animal_name', 'Hair', 'Feathers', 'Eggs',
    'Milk', 'Airbone', 'Aquati', 'Predator',
    'Toothed', 'Backbone', 'Breathes', 'Venomous',
    'Fins', 'Legs', 'Tail', 'Domestic', 'Catsize', 'Type'
]
df_remote

animal_name  Hair  Feathers  Eggs  Milk  Airbone  Aquati  Predator  Toothed  Backbone  Breathes  Venomous  Fins  Legs  Tail  Domestic  Catsize  Type
0      aardvark     1         0     0     1        0       0         1        1         1         1         0     0     4     0         0        1     1
1      antelope     1         0     0     1        0       0         0        1         1         1         0     0     4     1         0        1     1
2          bass     0         0     1     0        0       1         1        1         1         0         0     1     0     1         0        0     4
3          bear     1         0     0     1        0       0         1        1         1         1         0     0     4     0         0        1     1
4          boar     1         0     0     1        0       0         1        1         1         1         0     0     4     1         0        1     1
..          ...   ...       ...   ...   ...      ...     ...       ...      ...       ...       ...       ...   ...   ...   ...       ...      ...   ...
96      wallaby     1         0     0     1        0       0         0        1         1         1         0     0     2     1         0        1     1
97         wasp     1         0     1     0        1       0         0        0         0         1         1     0     6     0         0        0     6
98         wolf     1         0     0     1        0       0         1        1         1         1         0     0     4     1         0        1     1
99         worm     0         0     1     0        0       0         0        0         0         1         0     0     0     0         0        0     7
100        wren     0         1     1     0        1       0         0        0         1         1         0     0     2     1         0        0     2

[101 rows x 18 columns]

```
Deskrispi dataset:
* animal_name: Nama hewan yang sedang dianalisis dalam dataset.
* Hair: Indikator apakah hewan memiliki rambut atau bulu (0 = Tidak, 1 = Ya).
* Feathers: Indikator apakah hewan memiliki bulu (0 = Tidak, 1 = Ya).
* Eggs: Indikator apakah hewan bereproduksi dengan bertelur (0 = Tidak, 1 = Ya).
* Milk: Indikator apakah hewan menghasilkan susu untuk memberi makan anaknya (0 = Tidak, 1 = Ya).
* Airborne: Indikator apakah hewan dapat terbang atau hidup di udara (0 = Tidak, 1 = Ya).
* Aquatic: Indikator apakah hewan hidup di air atau memiliki sifat akuatik (0 = Tidak, 1 = Ya).
* Predator: Indikator apakah hewan merupakan predator atau pemangsa (0 = Tidak, 1 = Ya).
* Toothed: Indikator apakah hewan memiliki gigi (0 = Tidak, 1 = Ya).
* Backbone: Indikator apakah hewan memiliki tulang belakang atau merupakan vertebrata (0 = Tidak, 1 = Ya).
* Breathes: Indikator apakah hewan bernapas menggunakan paru-paru (0 = Tidak, 1 = Ya).
* Venomous: Indikator apakah hewan memiliki bisa atau racun (0 = Tidak, 1 = Ya).
* Fins: Indikator apakah hewan memiliki sirip (0 = Tidak, 1 = Ya).
* Legs: Jumlah kaki yang dimiliki hewan (nilai numerik, seperti 0, 2, 4, 6, dll.).
* Tail: Indikator apakah hewan memiliki ekor (0 = Tidak, 1 = Ya).
* Domestic: Indikator apakah hewan dapat didomestikasi atau dijinakkan (0 = Tidak, 1 = Ya).
* Catsize: Indikator apakah hewan berukuran seperti kucing atau lebih kecil (0 = Tidak, 1 = Ya).
* Type: Klasifikasi atau tipe hewan berdasarkan kategorisasi tertentu (nilai numerik yang merepresentasikan kategori, seperti mamalia, burung, reptil, dll.).
```

* Pembuatan DataFrame melalui *path* lokal

In [171]:
# Membaca file CSV
df_local = pd.read_csv(
    "sales.csv" # relative path dari file csv di lokal
)

df_local

Year  Product       line Product.1  type  Product.2  Order method     type.1 Retailer  country    Revenue
0   2004  Camping  Equipment   Cooking  Gear  TrailChef  Water    Bag  Telephone   United   States  315044.33
1   2004  Camping  Equipment   Cooking  Gear  TrailChef  Water    Bag  Telephone   Canada      NaN   14313.48
2   2004  Camping  Equipment   Cooking  Gear  TrailChef  Water    Bag  Telephone   Mexico      NaN  156644.47
3   2004  Camping  Equipment   Cooking  Gear  TrailChef  Water    Bag  Telephone   Brazil      NaN   59191.72
4   2004  Camping  Equipment   Cooking  Gear  TrailChef  Water    Bag  Telephone    Japan      NaN    7029.33
..   ...      ...        ...       ...   ...        ...    ...    ...        ...      ...      ...        ...
95  2004  Camping  Equipment   Cooking  Gear  TrailChef  Water    Bag       Mail  Finland      NaN    6615.84
96  2004  Camping  Equipment   Cooking  Gear  TrailChef  Water    Bag       Mail  Denmark      NaN   52613.47
97  2004  Camping  Equipment   Cooking  Gear  TrailChef  Water    Bag       Mail   France      NaN   41912.85
98  2004  Camping  Equipment   Cooking  Gear  TrailChef  Water    Bag       Mail  Germany      NaN   59479.91
99  2004  Camping  Equipment   Cooking  Gear  TrailChef  Water    Bag       Mail   United  Kingdom  156324.28

[100 rows x 12 columns]

### 2.2.6 Melihat cuplikan DataFrame

Berdasarkan hasil DataFrame sebelumnya, terdapat banyak data yang disertai dengan baris (...). Terdapat method `head()` yang dapat digunakan untuk melihat hanya 5 baris pertama dari DataFrame. Parameter dalam `head()` juga dapat diubah sesuai jumlah baris yang ingin ditampilkan. Selain itu, terdapat method `tail()` yang dapat digunakan untuk melihat 5 baris terakhir.

In [172]:
df_remote.head()

animal_name  Hair  Feathers  Eggs  Milk  Airbone  Aquati  Predator  Toothed  Backbone  Breathes  Venomous  Fins  Legs  Tail  Domestic  Catsize  Type
0    aardvark     1         0     0     1        0       0         1        1         1         1         0     0     4     0         0        1     1
1    antelope     1         0     0     1        0       0         0        1         1         1         0     0     4     1         0        1     1
2        bass     0         0     1     0        0       1         1        1         1         0         0     1     0     1         0        0     4
3        bear     1         0     0     1        0       0         1        1         1         1         0     0     4     0         0        1     1
4        boar     1         0     0     1        0       0         1        1         1         1         0     0     4     1         0        1     1

In [173]:
df_remote.tail()

animal_name  Hair  Feathers  Eggs  Milk  Airbone  Aquati  Predator  Toothed  Backbone  Breathes  Venomous  Fins  Legs  Tail  Domestic  Catsize  Type
96      wallaby     1         0     0     1        0       0         0        1         1         1         0     0     2     1         0        1     1
97         wasp     1         0     1     0        1       0         0        0         0         1         1     0     6     0         0        0     6
98         wolf     1         0     0     1        0       0         1        1         1         1         0     0     4     1         0        1     1
99         worm     0         0     1     0        0       0         0        0         0         1         0     0     0     0         0        0     7
100        wren     0         1     1     0        1       0         0        0         1         1         0     0     2     1         0        0     2

### 2.2.2 Menampilkan atribut dari objek DataFrame

#### 1. Menampilkan dimensi DataFrame dengan atribut `shape`

In [174]:
print("Dimensi dari df adalah", df_remote.shape)
print("df terdiri atas {} baris dan {} kolom.".format(df_remote.shape[0], df_remote.shape[1]))

Dimensi dari df adalah (101, 18)
df terdiri atas 101 baris dan 18 kolom.


#### 2. Menampilkan tipe data tiap kolom dengan atribut `dtypes`

In [175]:
df_remote.dtypes

animal_name    object
Hair            int64
Feathers        int64
Eggs            int64
Milk            int64
Airbone         int64
Aquati          int64
Predator        int64
Toothed         int64
Backbone        int64
Breathes        int64
Venomous        int64
Fins            int64
Legs            int64
Tail            int64
Domestic        int64
Catsize         int64
Type            int64
dtype: object

#### 3. Menampilkan statistik umum tiap kolom dengan method `describe()`

In [176]:
df_remote.describe()

Hair    Feathers        Eggs        Milk     Airbone      Aquati    Predator     Toothed    Backbone    Breathes    Venomous        Fins        Legs        Tail    Domestic     Catsize        Type
count  101.000000  101.000000  101.000000  101.000000  101.000000  101.000000  101.000000  101.000000  101.000000  101.000000  101.000000  101.000000  101.000000  101.000000  101.000000  101.000000  101.000000
mean     0.425743    0.198020    0.584158    0.405941    0.237624    0.356436    0.554455    0.603960    0.821782    0.792079    0.079208    0.168317    2.841584    0.742574    0.128713    0.435644    2.831683
std      0.496921    0.400495    0.495325    0.493522    0.427750    0.481335    0.499505    0.491512    0.384605    0.407844    0.271410    0.376013    2.033385    0.439397    0.336552    0.498314    2.102709
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000    1.000000
25%      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000    0.000000    1.000000    1.000000    0.000000    0.000000    2.000000    0.000000    0.000000    0.000000    1.000000
50%      0.000000    0.000000    1.000000    0.000000    0.000000    0.000000    1.000000    1.000000    1.000000    1.000000    0.000000    0.000000    4.000000    1.000000    0.000000    0.000000    2.000000
75%      1.000000    0.000000    1.000000    1.000000    0.000000    1.000000    1.000000    1.000000    1.000000    1.000000    0.000000    0.000000    4.000000    1.000000    0.000000    1.000000    4.000000
max      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000    1.000000    1.000000    1.000000    1.000000    1.000000    1.000000    8.000000    1.000000    1.000000    1.000000    7.000000

#### 4. Menampilkan statistik untuk kolom yang diinginkan dengan method `describe()`

In [177]:
df_remote['animal_name'].describe()

count      101
unique     100
top       frog
freq         2
Name: animal_name, dtype: object

#### 5. Menghitung jumlah elemen tidak null tiap kolom dengan method `count()`

In [178]:
print("Count untuk df_remote\n", df_remote.count())

Count untuk df_remote
 animal_name    101
Hair           101
Feathers       101
Eggs           101
Milk           101
Airbone        101
Aquati         101
Predator       101
Toothed        101
Backbone       101
Breathes       101
Venomous       101
Fins           101
Legs           101
Tail           101
Domestic       101
Catsize        101
Type           101
dtype: int64


Berdasarkan kode di atas, diketahui bahwa df_remote seluruhnya terhitung 101 baris, yang umumnya, berarti tidak ada nilai null.

### 2.2.3 Mengakses baris dan kolom dalam  DataFrame

Terdapat beberapa cara dalam mengakses kolom suatu DataFrame, diantaranya sebagai berikut.

#### 1. Mengakses kolom sebagai series

In [179]:
# Mengakses kolom sebagai Series
df_remote_hair = df_remote['Hair']
print(type(df_remote_hair))
df_remote_hair

<class 'pandas.core.series.Series'>


0      1
1      1
2      0
3      1
4      1
      ..
96     1
97     1
98     1
99     0
100    0
Name: Hair, Length: 101, dtype: int64

#### 2. Mengakses kolom sebagai DataFrame

In [180]:
# Mengakses kolom sebagai DataFrame
df_remote_eggs = df_remote[['Eggs']]
print(type(df_remote_eggs))
df_remote_eggs

<class 'pandas.core.frame.DataFrame'>


Eggs
0       0
1       0
2       1
3       0
4       0
..    ...
96      0
97      1
98      0
99      1
100     1

[101 rows x 1 columns]

#### 3. Mengakses beberapa kolom sebagai DataFrame

In [181]:
# Mengakses lebih dari 1 kolom sebagai DataFrame
df_hair_eggs = df_remote[['Hair', 'Eggs']]
df_hair_eggs

Hair  Eggs
0       1     0
1       1     0
2       0     1
3       1     0
4       1     0
..    ...   ...
96      1     0
97      1     1
98      1     0
99      0     1
100     0     1

[101 rows x 2 columns]

Selain mengakses kolom, terdapat pula beberapa cara untuk mengakses baris dan kolom dalam DataFrame, diantaranya menggunakan `loc` dan `iloc`.

Umumnya, `loc` digunakan untuk mengakses baris atau kolom berdasarkan label (nama kolom atau indeks). Indeks yang disebutkan dalam `loc` termasuk (inclusive) dalam pemilihan. Sedangkan `iloc` digunakan untuk mengakses data berdasarkan posisi integer baris dan kolom. Indeks yang disebutkan dalam `iloc` tidak termasuk (exclusive) pada slicing.

#### 1. Mengakses baris menggunakan `loc`

In [182]:
# Mengakses baris 1 sampai dengan 4 menggunakan loc
df_remote.loc[1:4]  # range inklusif

animal_name  Hair  Feathers  Eggs  Milk  Airbone  Aquati  Predator  Toothed  Backbone  Breathes  Venomous  Fins  Legs  Tail  Domestic  Catsize  Type
1    antelope     1         0     0     1        0       0         0        1         1         1         0     0     4     1         0        1     1
2        bass     0         0     1     0        0       1         1        1         1         0         0     1     0     1         0        0     4
3        bear     1         0     0     1        0       0         1        1         1         1         0     0     4     0         0        1     1
4        boar     1         0     0     1        0       0         1        1         1         1         0     0     4     1         0        1     1

#### 2. Mengakses baris 1 sampai dengan 4 menggunakan `iloc`

In [183]:
# Mengakses baris 1 sampai dengan 4 menggunakan iloc
df_remote.iloc[1:5] # range eksklusif

animal_name  Hair  Feathers  Eggs  Milk  Airbone  Aquati  Predator  Toothed  Backbone  Breathes  Venomous  Fins  Legs  Tail  Domestic  Catsize  Type
1    antelope     1         0     0     1        0       0         0        1         1         1         0     0     4     1         0        1     1
2        bass     0         0     1     0        0       1         1        1         1         0         0     1     0     1         0        0     4
3        bear     1         0     0     1        0       0         1        1         1         1         0     0     4     0         0        1     1
4        boar     1         0     0     1        0       0         1        1         1         1         0     0     4     1         0        1     1

#### 3. Mengakses baris 1 sampai dengan 4, namun hanya kolom hair dan eggs saja menggunakan `loc`

In [184]:
# Mengakses baris 1 sampai dengan 4, namun hanya kolom hair dan eggs saja, menggunakan loc
df_remote.loc[1:4, ["Hair", "Eggs"]]

Hair  Eggs
1     1     0
2     0     1
3     1     0
4     1     0

#### 4. Mengakses baris 1 sampai dengan 4, namun hanya kolom hair, feathers, dan eggs saja menggunakan `iloc`

In [185]:
# Mengakses baris 1 sampai dengan 4, namun hanya kolom hair, feathers, dan eggs saja, menggunakan iloc
df_remote.iloc[1:5, 1:4]

Hair  Feathers  Eggs
1     1         0     0
2     0         0     1
3     1         0     0
4     1         0     0

### 2.2.4 Mengakses Data Tertentu yang Memenuhi suatu Kondisi Dalam DataFrame

In [186]:
# Mengakses data dengan Hair sama dengan 1
df_remote[df_remote['Hair'] == 1]

animal_name  Hair  Feathers  Eggs  Milk  Airbone  Aquati  Predator  Toothed  Backbone  Breathes  Venomous  Fins  Legs  Tail  Domestic  Catsize  Type
0     aardvark     1         0     0     1        0       0         1        1         1         1         0     0     4     0         0        1     1
1     antelope     1         0     0     1        0       0         0        1         1         1         0     0     4     1         0        1     1
3         bear     1         0     0     1        0       0         1        1         1         1         0     0     4     0         0        1     1
4         boar     1         0     0     1        0       0         1        1         1         1         0     0     4     1         0        1     1
5      buffalo     1         0     0     1        0       0         0        1         1         1         0     0     4     1         0        1     1
6         calf     1         0     0     1        0       0         0        1         1         1         0     0     4     1         1        1     1
9         cavy     1         0     0     1        0       0         0        1         1         1         0     0     4     0         1        0     1
10     cheetah     1         0     0     1        0       0         1        1         1         1         0     0     4     1         0        1     1
17        deer     1         0     0     1        0       0         0        1         1         1         0     0     4     1         0        1     1
22    elephant     1         0     0     1        0       0         0        1         1         1         0     0     4     1         0        1     1
27    fruitbat     1         0     0     1        1       0         0        1         1         1         0     0     2     1         0        0     1
28     giraffe     1         0     0     1        0       0         0        1         1         1         0     0     4     1         0        1     1
29        girl     1         0     0     1        0       0         1        1         1         1         0     0     2     0         1        1     1
31        goat     1         0     0     1        0       0         0        1         1         1         0     0     4     1         1        1     1
32     gorilla     1         0     0     1        0       0         0        1         1         1         0     0     2     0         0        1     1
35     hamster     1         0     0     1        0       0         0        1         1         1         0     0     4     1         1        0     1
36        hare     1         0     0     1        0       0         0        1         1         1         0     0     4     1         0        0     1
39    honeybee     1         0     1     0        1       0         0        0         0         1         1     0     6     0         1        0     6
40    housefly     1         0     1     0        1       0         0        0         0         1         0     0     6     0         0        0     6
44     leopard     1         0     0     1        0       0         1        1         1         1         0     0     4     1         0        1     1
45        lion     1         0     0     1        0       0         1        1         1         1         0     0     4     1         0        1     1
47        lynx     1         0     0     1        0       0         1        1         1         1         0     0     4     1         0        1     1
48        mink     1         0     0     1        0       1         1        1         1         1         0     0     4     1         0        1     1
49        mole     1         0     0     1        0       0         1        1         1         1         0     0     4     1         0        0     1
50    mongoose     1         0     0     1        0       0         1        1         1         1         0     0     4     1         0        1     1
51        moth     1         0     1     0        1

In [187]:
# Mengakses data dengan Hair sama dengan 1 cm dan Type lebih dari 1
df_remote[(df_remote['Hair'] == 1) & (df_remote['Type'] > 3)]

animal_name  Hair  Feathers  Eggs  Milk  Airbone  Aquati  Predator  Toothed  Backbone  Breathes  Venomous  Fins  Legs  Tail  Domestic  Catsize  Type
39    honeybee     1         0     1     0        1       0         0        0         0         1         1     0     6     0         1        0     6
40    housefly     1         0     1     0        1       0         0        0         0         1         0     0     6     0         0        0     6
51        moth     1         0     1     0        1       0         0        0         0         1         0     0     6     0         0        0     6
97        wasp     1         0     1     0        1       0         0        0         0         1         1     0     6     0         0        0     6

### 2.2.5 Menangani Missing Values

Nilai null atau *missing values* merujuk pada data yang kosong atau tidak terisi. Hal ini dapat terjadi karena informasi tersebut tidak disediakan, sulit ditemukan, atau memang tidak tersedia. *Missing values* juga dapat direpresentasikan dengan istilah seperti "NA" atau "NaN".

#### 1. Kondisi Tidak Ada *Missing Values*

In [188]:
# Menampilkan jumlah missing values tiap kolom
print("Count missing values untuk df_remote\n", df_remote.isnull().sum())

Count missing values untuk df_remote
 animal_name    0
Hair           0
Feathers       0
Eggs           0
Milk           0
Airbone        0
Aquati         0
Predator       0
Toothed        0
Backbone       0
Breathes       0
Venomous       0
Fins           0
Legs           0
Tail           0
Domestic       0
Catsize        0
Type           0
dtype: int64


#### 2. Kondisi Terdapat *Missing Values*

In [189]:
# Menampilkan jumlah missing values tiap kolom
print("Count missing values untuk df_local\n", df_local.isnull().sum())

Count missing values untuk df_local
 Year          0
Product       0
line          0
Product.1     0
type          0
Product.2     0
Order         0
method        0
type.1        0
Retailer      0
country      91
Revenue       0
dtype: int64


Berdasarkan kode di atas, diketahui  bahwa ada kolom "country" yang memiliki nilai null dengan jumlah nilai null sebanyak 91 buah.

Ada beberapa pendekatan untuk menangani missing values, berikut pendekatan yang umum digunakan:

Mengisi missing values dengan nilai tertentu menggunakan method `fillna()`
Menghapus (drop) baris atau kolom yang mengandung missing values. Gunakan `dropna()` untuk menghapus baris yang mengandung missing values, dan `dropna(axis='columns')` untuk menghapus kolom yang mengandung missing values.

Contoh-contoh di bawah akan berfokus pada kolom "country".


* Mengisi data menggunakan method `fillna()`

Terdapat tiga cara untuk melakukan method `fillna()`, diantaranya sebagai berikut.

    - Mean, umumnya dapat digunakan untuk mengisi data numerikal yang memiliki distribusi normal.

    - Median, umumnya dapat digunakan untuk mengisi data numerikal yang memiliki distribusi skewed.
    
    - Mode, umumnya dapat digunakan untuk mengisi data kategorikal.

Untuk mengisi *missing values* dalam data, maka akan digunakan mode sebagai contoh.

In [190]:
# Salin DataFrame
df_local_fillna = df_local.copy()

# Mendapatkan nilai modus untuk kolom 'country'
mode = df_local_fillna['country'].mode()[0]

# Mengisi missing values dengan nilai modus
df_local_fillna['country'].fillna(mode, inplace=True)

# Menampilkan 5 baris pertama
df_local_fillna.head(5)

C:\Users\Asus\AppData\Local\Temp\ipykernel_5308\3290560918.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_local_fillna['country'].fillna(mode, inplace=True)


Year  Product       line Product.1  type  Product.2  Order method     type.1 Retailer  country    Revenue
0  2004  Camping  Equipment   Cooking  Gear  TrailChef  Water    Bag  Telephone   United   States  315044.33
1  2004  Camping  Equipment   Cooking  Gear  TrailChef  Water    Bag  Telephone   Canada  Kingdom   14313.48
2  2004  Camping  Equipment   Cooking  Gear  TrailChef  Water    Bag  Telephone   Mexico  Kingdom  156644.47
3  2004  Camping  Equipment   Cooking  Gear  TrailChef  Water    Bag  Telephone   Brazil  Kingdom   59191.72
4  2004  Camping  Equipment   Cooking  Gear  TrailChef  Water    Bag  Telephone    Japan  Kingdom    7029.33

* Menghapus baris atau kolom dengan menggunakan `dropna()`

In [191]:
# dropna untuk menghapus baris yang mengandung missing values
df_local_drop = df_local.copy()
df_local_drop = df_local_drop.dropna()
df_local_drop.head(5)

Year  Product       line Product.1  type  Product.2  Order method     type.1 Retailer  country    Revenue
0   2004  Camping  Equipment   Cooking  Gear  TrailChef  Water    Bag  Telephone   United   States  315044.33
15  2004  Camping  Equipment   Cooking  Gear  TrailChef  Water    Bag  Telephone   United  Kingdom   62800.36
21  2004  Camping  Equipment   Cooking  Gear  TrailChef  Water    Bag      visit   United   States    7367.64
36  2004  Camping  Equipment   Cooking  Gear  TrailChef  Water    Bag      visit   United  Kingdom   52776.36
42  2004  Camping  Equipment   Cooking  Gear  TrailChef  Water    Bag        Web   United   States  340867.26

# Pertanyaan Pandas

Jawab setiap pertanyaan pada cell di bawah cell pertanyaan. Jawaban boleh lebih dari 1 cell dan juga kombinasi antara cell kode atau markdown jika memang diperlukan sebagai penjelasan jawaban. Gunakan dataset School_Nutrition_Programs.csv yang dilampirkan di SCELE untuk mengerjakan soal-soal berikut.

In [192]:
import pandas as pd
import numpy as np

## Nomor 1

Buka dataset  School_Nutrition_Programs.csv sebagai dataframe dan tampilkan 15 baris terarkhir dari dataframe tersebut.

```
Deskripsi Dataset:
* Tahun Program: Tahun tinjauan program terkait (2015-2016).
* ID CE: Pengenal unik untuk Otoritas Makanan Sekolah (SFA).
* Nama CE: Nama Otoritas Makanan Sekolah (SFA).
* Wilayah PKB: Wilayah di bawah Pusat Layanan Pendidikan (ESC) yang mengawasi SFA.
* ID Peninjauan: Pengenal unik untuk tinjauan spesifik yang dilakukan.
* Tanggal Tinjauan: Tanggal pelaksanaan tinjauan.
* Area Temuan: Area atau kategori di mana temuan dibuat selama peninjauan (misalnya, kepatuhan, standar gizi).
* Nomor Pertanyaan: Pertanyaan spesifik dari tinjauan administratif yang terkait dengan temuan.
* Pertanyaan: Teks pertanyaan tinjauan administratif yang terkait dengan temuan.
```



Tujuan:
Dataset ini membantu pengguna memahami jenis-jenis temuan yang dilaporkan selama tinjauan administratif terhadap SFA, yang menyoroti isu-isu kepatuhan dalam NSLP. Data ini dapat bermanfaat bagi peneliti, pembuat kebijakan, atau siapa saja yang tertarik dengan administrasi dan pengawasan program gizi sekolah.


In [25]:
import pandas as pd
# Membaca dataset pada CSV
file_path = "School_Nutrition_Programs.csv"
df = pd.read_csv(file_path)

# Menampilkan 15 baris terakhir
df.tail(15)

Program Year  CE ID                                   CE Name  \
1594  2015 - 2016   1029                           CASTLEBERRY ISD   
1595  2015 - 2016   5427                ERATH EXCELS ACADEMY, INC.   
1596  2015 - 2016   5427                ERATH EXCELS ACADEMY, INC.   
1597  2015 - 2016   5427                ERATH EXCELS ACADEMY, INC.   
1598  2015 - 2016   5427                ERATH EXCELS ACADEMY, INC.   
1599  2015 - 2016   5427                ERATH EXCELS ACADEMY, INC.   
1600  2015 - 2016   5427                ERATH EXCELS ACADEMY, INC.   
1601  2015 - 2016   5427                ERATH EXCELS ACADEMY, INC.   
1602  2015 - 2016    906                               FARWELL ISD   
1603  2015 - 2016    906                               FARWELL ISD   
1604  2015 - 2016    906                               FARWELL ISD   
1605  2015 - 2016    906                               FARWELL ISD   
1606  2015 - 2016    906                               FARWELL ISD   
1607  2015 - 2016    829        TEXAS SERENITY ACADEMY (CONROE,TX)   
1608  2015 - 2016    251  ACADEMY OF AMERICA DBA ACADEMY OF DALLAS   

      ESC Region  Review ID Review Date  \
1594          11      14445  04/28/2016   
1595          11      21234  04/28/2016   
1596          11      21234  04/28/2016   
1597          11      21234  04/28/2016   
1598          11      21234  04/28/2016   
1599          11      21234  04/28/2016   
1600          11      21234  04/28/2016   
1601          11      21234  04/28/2016   
1602          16      14325  04/28/2016   
1603          16      14325  04/28/2016   
1604          16      14325  04/28/2016   
1605          16      14325  04/28/2016   
1606          16      14325  04/28/2016   
1607           4      14250  04/28/2016   
1608          10      22590  06/02/2016   

                                          Finding Area Question Number  \
1594                       Additional Review Questions               3   
1595          100 - Certification and Benefit Issuance             126   
1596          100 - Certification and Benefit Issuance             138   
1597          100 - Certification and Benefit Issuance             123   
1598                                1400 - Food Safety            1400   
1599                1500 - Reporting and Recordkeeping            1502   
1600                                800 - Civil Rights             803   
1601          Resource Mgt Comprehensive Review (2016)               7   
1602          100 - Certification and Benefit Issuance             126   
1603          100 - Certification and Benefit Issuance             137   
1604          100 - Certification and Benefit Issuance             128   
1605                          1700 - Afterschool Snack            1707   
1606  400 - Meal Components and Quantities - Breakfast             401   
1607                       Additional Review Questions               1   
1608  400 - Meal Components and Quantities - Breakfast             403   

     Question\n(For more details, USDA provides information on the forms referenced in this column on their Website.)  
1594  Was the competitive procurement procedures use...                                                                
1595  a. Certification and Benefit Issuance Review M...                                                                
1596  Did the SFA update the benefit issuance docume...                                                                
1597  For each question on the Off-Site Assessment T...                                                                
1598  a. Does the written food safety plan contain t...                                                                
1599  Did the SFA maintain sufficient records to doc...                                                                
1600  What is the SFA’s procedure for receiving and ...                                                                
1601  Was the SFA able to separate its program foo

## Nomor 2

Tampilkan ukuran DataFrame tersebut, tipe data setiap kolom, serta statistik deskriptif untuk kolom-kolom di atas.

In [26]:
import pandas as pd
df.columns = df.columns.str.strip().str.replace("\n", " ").str.replace("\r", " ")
df = df.loc[:, ~df.columns.str.contains("For more details", case=False)]
df.tail(15)
df_shape = df.shape
print("DataFrame Shape:", df_shape)

# Tipe data tiap kolom
tipe_data = df.dtypes
print("\nData Types:")
print(tipe_data)

# Deskriptif statistik tiap kolom
df_describe = df.describe()
print("")
print("Descriptive Statistics: ")
print(df_describe)


DataFrame Shape: (1609, 8)

Data Types:
Program Year       object
CE ID               int64
CE Name            object
ESC Region          int64
Review ID           int64
Review Date        object
Finding Area       object
Question Number    object
dtype: object

Descriptive Statistics: 
             CE ID  ESC Region     Review ID
count  1609.000000  1609.00000   1609.000000
mean    864.846489    10.36358  15526.676818
std     903.558032     5.52990   2086.934338
min       1.000000     1.00000  13449.000000
25%     332.000000     6.00000  13980.000000
50%     733.000000    10.00000  14477.000000
75%    1095.000000    15.00000  18207.000000
max    5427.000000    20.00000  22590.000000


## Nomor 3

Tampilkan seluruh data dalam kolom `Review ID` yang memiliki nilai lebih dari 20000 pada dataset tersebut.

In [28]:
import pandas as pd
review_id_diatas_20000 = df[df['Review ID'] > 20000]
print("Data dengan Review ID lebih dari 20000:")
print(" ")
print(review_id_diatas_20000)

Data dengan Review ID lebih dari 20000:
 
     Program Year  CE ID                                   CE Name  \
402   2015 - 2016    405                             LA MARQUE ISD   
403   2015 - 2016    405                             LA MARQUE ISD   
404   2015 - 2016    405                             LA MARQUE ISD   
405   2015 - 2016    405                             LA MARQUE ISD   
406   2015 - 2016    405                             LA MARQUE ISD   
1275  2015 - 2016    735                                HARDIN ISD   
1276  2015 - 2016    735                                HARDIN ISD   
1277  2015 - 2016    735                                HARDIN ISD   
1492  2015 - 2016   5376       RICHARD MILBURN ACADEMY TEXAS, INC.   
1493  2015 - 2016   5376       RICHARD MILBURN ACADEMY TEXAS, INC.   
1494  2015 - 2016   5376       RICHARD MILBURN ACADEMY TEXAS, INC.   
1495  2015 - 2016   5376       RICHARD MILBURN ACADEMY TEXAS, INC.   
1496  2015 - 2016   5376       RICHARD MILBURN A

## Nomor 4

Tunjukkan ada berapa  unik pada dataset tersebut. Kemudian  apa yang paling banyak muncul dan berapa banyak kemunculannya?

In [32]:
import pandas as pd
# Menghitung jumlah CE Name unik
nama_ce_unik = df['CE Name'].nunique()
print("Jumlah CE Name unik:", nama_ce_unik)
print(" ")

# Menentukan CE yang paling banyak muncul
ce_terbanyak = df['CE Name'].value_counts().idxmax()
frekuensi_muncul = df['CE Name'].value_counts().max()
print("CE yang paling banyak muncul:", ce_terbanyak)
print(" ")
print("Jumlah kemunculan:", frekuensi_muncul)

Jumlah CE Name unik: 461
 
CE yang paling banyak muncul: MERIDIAN WORLD SCHOOL LLC
 
Jumlah kemunculan: 18


## Nomor 5

Tampilkan seluruh data dalam kolom `Finding Area` yang mengandung angka "1400".

In [ ]:
import pandas as pd
data_mengandung_140 = df[df['Finding Area'].astype(str).str.contains("1400", na=False)]

# Menampilkan hasil
print("Data dengan 'Finding Area' mengandung angka 1400: ")
print(" ")
print(data_mengandung_140)

# Dear asdos, kolom output ESC Region sampai Question Number jadi kebelah 2 ke bawah ya 
# soalnya ga muat ke samping, kayanya output lain ada beberapa yg spt ini juga (cmiiw)

Data dengan 'Finding Area' mengandung angka 1400: 
 
     Program Year  CE ID                                      CE Name  \
3     2015 - 2016   1283  HARRIS COUNTY JUVENILE PROBATION DEPARTMENT   
16    2015 - 2016   1340        MONTGOMERY COUNTY JUVENILE DEPARTMENT   
24    2015 - 2016   1251     YOUTH AND FAMILY ENRICHMENT CENTERS, INC   
41    2015 - 2016   1188            NEW HORIZONS RANCH AND CENTER INC   
42    2015 - 2016   1188            NEW HORIZONS RANCH AND CENTER INC   
...           ...    ...                                          ...   
1519  2015 - 2016    603                             MILLER GROVE ISD   
1524  2015 - 2016   1311                   SACRED HEART SCHOOL-UVALDE   
1570  2015 - 2016    977                                      IRA ISD   
1586  2015 - 2016    908                                LAZBUDDIE ISD   
1598  2015 - 2016   5427                   ERATH EXCELS ACADEMY, INC.   

      ESC Region  Review ID Review Date        Finding Area Question N

## Nomor 6

Buatlah dataframe baru dari data dataset tersebut yang terdiri dari kolom `Program Year`, `CE Name`, `Review ID`, `Review Date`, dan `Finding Area`. Serta tampilkan dimensi dari dataframe baru tersebut.

In [34]:
import pandas as pd

df_baru = df[['Program Year', 'CE Name', 'Review ID', 'Review Date', 'Finding Area']].copy()

#Print Output
print("DataFrame baru:")
print(" ")
print(df_baru.head(8))

# Dimensi Dataframe baru
df_shape_updated = (8, df_baru.shape[1])
print("\nDimensi DataFrame baru:", df_shape_updated)

DataFrame baru:
 
  Program Year                                      CE Name  Review ID  \
0  2015 - 2016         CHILDREN'S AID SOCIETY OF WEST TEXAS      14667   
1  2015 - 2016         CHILDREN'S AID SOCIETY OF WEST TEXAS      14667   
2  2015 - 2016         CHILDREN'S AID SOCIETY OF WEST TEXAS      14667   
3  2015 - 2016  HARRIS COUNTY JUVENILE PROBATION DEPARTMENT      14658   
4  2015 - 2016  HARRIS COUNTY JUVENILE PROBATION DEPARTMENT      14658   
5  2015 - 2016  HARRIS COUNTY JUVENILE PROBATION DEPARTMENT      14658   
6  2015 - 2016  HARRIS COUNTY JUVENILE PROBATION DEPARTMENT      14658   
7  2015 - 2016  HARRIS COUNTY JUVENILE PROBATION DEPARTMENT      14658   

  Review Date                                      Finding Area  
0  09/07/2015                          1700 - Afterschool Snack  
1  09/07/2015                  300 - Meal Counting and Claiming  
2  09/07/2015      400 - Meal Components and Quantities - Lunch  
3  09/10/2015                                1400 -

## Nomor 7

Buatlah dataframe baru dari dataframe tersebut dengan mengubah kolom `Review Date` menjadi `Review Year` dan mengubah seluruh nilainya dalam bentuk tahun

In [35]:
# Asumsi: Dataframe yang ingin diperbarui dan 
# diubah kolom `Review Date` menjadi `Review Year 
# adalah dataframe baru dari nomor 6.(Sorry 
# soalnya masih agak bingung "dataframe tersebut" 
# tuh merujuk ke dataframe baru atau yang ada di 
# dataset)

import pandas as pd

df_baru = df[['Program Year', 'CE Name', 'Review ID', 'Review Date', 'Finding Area']].copy()

# Review Date menjadi tahun saja
df_baru['Review Year'] = pd.to_datetime(df_baru['Review Date']).dt.year
df_baru.drop(columns=['Review Date'], inplace=True)

print("DataFrame baru:")
print(" ")
print(df_baru.head(8))

DataFrame baru:
 
  Program Year                                      CE Name  Review ID  \
0  2015 - 2016         CHILDREN'S AID SOCIETY OF WEST TEXAS      14667   
1  2015 - 2016         CHILDREN'S AID SOCIETY OF WEST TEXAS      14667   
2  2015 - 2016         CHILDREN'S AID SOCIETY OF WEST TEXAS      14667   
3  2015 - 2016  HARRIS COUNTY JUVENILE PROBATION DEPARTMENT      14658   
4  2015 - 2016  HARRIS COUNTY JUVENILE PROBATION DEPARTMENT      14658   
5  2015 - 2016  HARRIS COUNTY JUVENILE PROBATION DEPARTMENT      14658   
6  2015 - 2016  HARRIS COUNTY JUVENILE PROBATION DEPARTMENT      14658   
7  2015 - 2016  HARRIS COUNTY JUVENILE PROBATION DEPARTMENT      14658   

                                       Finding Area  Review Year  
0                          1700 - Afterschool Snack         2015  
1                  300 - Meal Counting and Claiming         2015  
2      400 - Meal Components and Quantities - Lunch         2015  
3                                1400 - Food Sa

## Nomor 8

Dari dataset pada nomor 1 tersebut, tampilkan 5 data yang memiliki `ESC Region` yang paling rendah.

In [ ]:
import pandas as pd

# Menampilkan 5 data dengan ESC Region paling rendah
esc_region_terendah = df.nsmallest(5, 'ESC Region')

# Menampilkan hasil
print("5 Data dengan ESC Region paling rendah: ")
print(" ")
print(esc_region_terendah)
print(" ")

5 Data dengan ESC Region paling rendah: 
 
    Program Year  CE ID                    CE Name  ESC Region  Review ID  \
36   2015 - 2016   1198  AMIKIDS RIO GRANDE VALLEY           1      14769   
37   2015 - 2016   1198  AMIKIDS RIO GRANDE VALLEY           1      14769   
38   2015 - 2016   1198  AMIKIDS RIO GRANDE VALLEY           1      14769   
39   2015 - 2016   1198  AMIKIDS RIO GRANDE VALLEY           1      14769   
135  2015 - 2016   1143                 LASARA ISD           1      14552   

    Review Date                                      Finding Area  \
36   09/23/2015                          1700 - Afterschool Snack   
37   09/23/2015                          1700 - Afterschool Snack   
38   09/23/2015  400 - Meal Components and Quantities - Breakfast   
39   09/23/2015                  700 - Resource Management (2015)   
135  10/14/2015      300 - Meal Counting and Claiming - Breakfast   

    Question Number  
36             1706  
37             1707  
38           

# **3. Pengenalan NumPy**

NumPy merupakan library Python yang umum digunakan untuk melakukan komputasi saintifik, pengolahan, serta analisis data numerik karena performa dan kemudahannya. NumPy menyerupai list dalam Python, namun NumPy memiliki beberapa kelebihan lain. NumPy  menyediakan fungsi-fungsi high-level untuk melakukan berbagai perhitungan secara efisien, seperti penjumlahan, pengurutan, dan sebagainya pada struktur data yang disebut array. Hal ini menyebabkan NumPy menjadi salah satu library yang banyak digunakan dalam proses analisis data.

In [233]:
# import library NumPy
import numpy as np

## 3.1 Pembuatan NumPy Array

Secara umum, array pada NumPy merupakan struktur data yang mirip dengan List, tetapi memiliki kemampuan yang lebih kuat dan efisien. Array bisa memiliki lebih dari satu dimensi, yang mana elemennya bisa berarti sebuah array juga, yang bisa memiliki elemen array juga, dan begitupun seterusnya sehingga memungkinkan penyimpanan struktur data dengan dimensi yang kompleks.

### 3.1.1 NumPy Array Satu Dimensi

NumPy Array Satu Dimensi adalah array satu dimensi yang serupa dengan list. NumPy Array Satu Dimensi dapat dibuat dari list atau tuple. Untuk membuat objek array, dapat digunakan fungsi array(n) dengan n berupa koleksi seperti list, tuple, dan sebagainya seperti berikut.

#### 1. Membuat Array dengan List

In [234]:
arr = np.array([5, 10, 15, 20, 25])
arr

array([ 5, 10, 15, 20, 25])

Untuk melihat tipe dari array tersebut dapat menggunakan cara sebagai berikut.

In [236]:
print(type(arr))

<class 'numpy.ndarray'>


#### 2. Membuat Array dengan Tuple

In [238]:
arr = np.array((1,2,3,4,5))
arr

array([1, 2, 3, 4, 5])

In [ ]:
print(type(arr))

<class 'numpy.ndarray'>


Terdapat pula beberapa fungsi bawaan untuk membuat objek array yang dapat digunakan sesuai kebutuhan.

In [239]:
# Membuat array dengan nilai 0 sebanyak 5 buah
print("np.zeros(4) : ",np.zeros(5))

# Membuat array dengan nilai 1 sebanyak 5 buah
print("np.ones(4) : ",np.ones(5))

# Membuat array dengan nilai dalam range 1 sampai 15 dengan step sebesar 5
print("np.arange(1,15,3) : ",np.arange(1,15,5))

# Membuat array dengan nilai dalam range 1 sampai 10 sebanyak 4 dengan interval yang sama
print("np.linspace(1,10,4) : ",np.linspace(1,10,4))

np.zeros(4) :  [0. 0. 0. 0. 0.]
np.ones(4) :  [1. 1. 1. 1. 1.]
np.arange(1,15,3) :  [ 1  6 11]
np.linspace(1,10,4) :  [ 1.  4.  7. 10.]


### 3.1.2 NumPy Array Dua Dimensi

Array multidimensi di NumPy merepresentasikan data dalam bentuk tabel, matriks, atau bahkan tensor dengan lebih dari dua dimensi.

In [241]:
multi_dim_arr = np.array([[1,5,10, 15], [20,25,30, 35], [40,45,50, 55], [60,65,70, 75]])
multi_dim_arr

array([[ 1,  5, 10, 15],
       [20, 25, 30, 35],
       [40, 45, 50, 55],
       [60, 65, 70, 75]])

## 3.2 Menampilkan Atribut NumPy Array

NumPy array memiliki sejumlah atribut yang berguna untuk memahami struktur dan karakteristik data yang disimpan di dalamnya, beberapa diantaranya sebagai berikut.

In [243]:
print(multi_dim_arr)

print()

# Menunjukkan ukuran array
print("multi_dim_arr.size:", multi_dim_arr.size)

# Menunjukkan jumlah dimensi atau rank dari sebuah array
print("multi_dim_arr.ndim:", multi_dim_arr.ndim)

# Mengetahui ukuran dari setiap dimensi array
print("multi_dim_arr.shape:", multi_dim_arr.shape)

[[ 1  5 10 15]
 [20 25 30 35]
 [40 45 50 55]
 [60 65 70 75]]

multi_dim_arr.size: 16
multi_dim_arr.ndim: 2
multi_dim_arr.shape: (4, 4)


### 3.3 Periksa Tipe Data

Setiap data memiliki tipe data tertentu yang ditentukan oleh atribut dtype. Tipe data ini menentukan jenis nilai yang dapat disimpan, seperti bilangan bulat (integer), bilangan desimal (float), atau tipe data lainnya.

In [245]:
# Tipe Data List
lst = [5,10,15,20,25]
print(f"type(lst): {type(lst)}")

# Tipe Data array
arr = np.array(lst)
print(f"type(arr): {type(arr)}")

type(lst): <class 'list'>
type(arr): <class 'numpy.ndarray'>


Selain fungsi type(), dapat juga menggunakan atribut dtype untuk mengetahui tipe data yang ada di dalam array.

In [246]:
# Cek tipe data dari array
print(f"arr.dtype: {arr.dtype}")

arr.dtype: int64


### 3.4 Indexing, Slicing, dan Assigning Value pada NumPy Array

Memanggil kembali array dan multi dimensi array yang telah dibuat sebelumnya

In [247]:
arr

array([ 5, 10, 15, 20, 25])

In [248]:
multi_dim_arr

array([[ 1,  5, 10, 15],
       [20, 25, 30, 35],
       [40, 45, 50, 55],
       [60, 65, 70, 75]])

#### 3.3.1 Indexing

In [249]:
# Mengakses elemen indeks ke-4 dari array
arr[4]

np.int64(25)

In [250]:
# Mengakses elemen baris ke-1 dan kolom ke-2 dari multi dimensi array
print(multi_dim_arr[2,2])

# Cara lain
print(multi_dim_arr[2][2])

50
50


#### 3.3.2 Slicing

In [253]:
# slice elemen dari indeks ke-1 sampai ke-5
arr[1:6]

array([10, 15, 20, 25])

In [252]:
# Slice elemen dari baris ketiga, kolom 2 sampai 3
multi_dim_arr[2,1:3]

array([45, 50])

In [254]:
# Slice kolom ketiga
multi_dim_arr[:,2]

array([10, 30, 50, 70])

### 3.3.3 Assigning Values

In [255]:
# Mengubah value elemen ke-4 dari array
arr[3] = 100
arr

array([  5,  10,  15, 100,  25])

In [256]:
# Mengubah value elemen baris ke-3 dan kolom ke-4 dari multi dimensi array
multi_dim_arr[2,3] = 100
multi_dim_arr

array([[  1,   5,  10,  15],
       [ 20,  25,  30,  35],
       [ 40,  45,  50, 100],
       [ 60,  65,  70,  75]])

## 3.4 Operasi Matematika pada NumPy Array

In [257]:
arr_1 = np.array([12, 15, 18, 21, 24])
arr_2 = np.array([28, 32, 36, 40, 44])

### 3.4.1 Penjumlahan Dua Buah Array

In [258]:
# Menjumlahkan dua buah array
result = arr_1 + arr_2
result

array([40, 47, 54, 61, 68])

### 3.4.2 Pengurangan Dua Buah Array

In [259]:
# Mengurangkan dua buah array
result = arr_2 - arr_1
result

array([16, 17, 18, 19, 20])

### 3,4,3 Perkalian Dua Buah Array

In [260]:
# Perkalian dua buah array
result = arr_1 * arr_2
result

array([ 336,  480,  648,  840, 1056])

### 3.4.4 Penjumlahan Array dengan angka tertentu

In [261]:
# Menjumlahkan setiap elemen array dengan 10
result = arr_1 + 10
result

array([22, 25, 28, 31, 34])

### 3.4.5 Perkalian Array dengan angka tertentu

In [262]:
# Mengalikan setiap elemen array dengan 10
result = arr_1 * 10
result

array([120, 150, 180, 210, 240])

### 3.4.6 Dot Product Dua Buah Array

In [263]:
# Dot product dua buah array
result = np.dot(arr_1, arr_2)
result

np.int64(3360)

Operasi di atas dapat dilakukan pada array 1 dimensi maupun multidimensi. Kemudian, berikut ini adalah beberapa fungsi matematika yang dapat digunakan pada NumPy Array.

In [21]:

import numpy as np

matrix = np.array([[2, 4, 6],
                   [1, 3, 5],
                   [7, 8, 9]])

print("Original Matrix:")
print(matrix)
print()

# Transpose matrix
print("Transpose Matrix:")
transpose_matrix = np.transpose(matrix)
print(transpose_matrix)
print()

# Invers matrix (hanya jika determinan tidak nol)
try:
    print("Inverse Matrix:")
    inverse_matrix = np.linalg.inv(matrix)
    print(inverse_matrix)
except np.linalg.LinAlgError:
    print("Matrix tidak memiliki invers (determinannya nol).")
print()

# Menghitung determinan matriks
print("Determinant of Matrix:")
det = np.linalg.det(matrix)
print(det)
print()

# Menghitung rank matriks
print("Rank of Matrix:")
rank = np.linalg.matrix_rank(matrix)
print(rank)
print()

# Menghitung eigenvalues dan eigenvectors
print("Eigenvalues and Eigenvectors:")
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)


Original Matrix:
[[2 4 6]
 [1 3 5]
 [7 8 9]]

Transpose Matrix:
[[2 1 7]
 [4 3 8]
 [6 5 9]]

Inverse Matrix:
Matrix tidak memiliki invers (determinannya nol).

Determinant of Matrix:
0.0

Rank of Matrix:
2

Eigenvalues and Eigenvectors:
Eigenvalues: [ 1.61651514e+01 -2.16515139e+00  1.74647471e-16]
Eigenvectors:
 [[ 0.44718316  0.43198683  0.40824829]
 [ 0.34705394  0.58271178 -0.81649658]
 [ 0.8243669  -0.68835628  0.40824829]]


## 3.5 Operasi Statistik pada NumPy Array

In [19]:
arr = np.array([5, 10, 15, 20, 25, 30, 35, 40, 45, 50,
                55, 60, 65, 70, 75, 80, 85, 90, 95, 100])
arr

array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100])

In [18]:
import numpy as np

arr = np.array([5, 10, 15, 20, 25, 30, 35, 40, 45, 50,
                55, 60, 65, 70, 75, 80, 85, 90, 95, 100])
arr

# Nilai rata-rata
print("Rata-rata:", np.mean(arr))

# Nilai median
print("Median:", np.median(arr))

# Nilai maksimum
print("Maksimum:", np.max(arr))

# Nilai standar deviasi
print("Standar deviasi:", np.std(arr))

# Nilai percentile
print("Percentile 75:", np.percentile(arr, 75))

# Nilai unik
print("Nilai unik:", np.unique(arr))

Rata-rata: 52.5
Median: 52.5
Maksimum: 100
Standar deviasi: 28.83140648667699
Percentile 75: 76.25
Nilai unik: [  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100]


# Pertanyaan NumPy

## Nomor 1

Perhatikan array multidimensi berikut.

In [ ]:
arr_1 = np.array([
    [7, 8, 9, 4, 3],
    [5, 6, 2, 1, 0],
    [3, 8, 4, 7, 2],
    [9, 3, 5, 6, 1],
    [0, 1, 2, 8, 4]
])

Modifikasi lah array di atas sehingga menjadi dua buah matriks baru, matriks diagonal dan matriks segitiga atas.

In [15]:
import numpy as np

arr_1 = np.array([
    [7, 8, 9, 4, 3],
    [5, 6, 2, 1, 0],
    [3, 8, 4, 7, 2],
    [9, 3, 5, 6, 1],
    [0, 1, 2, 8, 4]
])

matriks_diagonal = np.diag(np.diag(arr_1))
matriks_segitiga_atas = np.triu(arr_1)

# Menampilkan output
print("Matriks Diagonal:")
print(matriks_diagonal, "\n")

print("Matriks Segitiga Atas:")
print(matriks_segitiga_atas)


Matriks Diagonal:
[[7 0 0 0 0]
 [0 6 0 0 0]
 [0 0 4 0 0]
 [0 0 0 6 0]
 [0 0 0 0 4]] 

Matriks Segitiga Atas:
[[7 8 9 4 3]
 [0 6 2 1 0]
 [0 0 4 7 2]
 [0 0 0 6 1]
 [0 0 0 0 4]]


## Nomor 2

Terdapat beberapa *array* multidimensi sebagai berikut.

In [287]:
A = np.array([[7, 8, 5, 3], [2, 9, 4, 6], [3, 7, 1, 8], [5, 2, 6, 4]])
B = np.array([[3, 6, 8, 2], [4, 5, 7, 1], [9, 2, 3, 6], [1, 7, 5, 8]])
C = np.array([[5, 9, 3, 7], [1, 6, 4, 2], [8, 3, 5, 1], [2, 7, 9, 4]])
D = np.array([[6, 3, 5, 8], [2, 7, 9, 4], [1, 8, 6, 2], [5, 4, 3, 7]])

Dari ketiga multidimensi array di atas, lakukanlah langkah-langkah berikut ini.
1. Cari absolute dari pengurangan antara A dan C yang kemudian dijumlahi hasil pengurangan B dan D
2. Buat matrix baru yang isinya adalah hasil kuadrat tiap elemen dari matrix pada langkah 1
3. Jalankan operasi invers pada matrix pada langkah 2
4. Terapkan operasi penjumlahan antara matrix pada langkah 3 dengan matriks C
5. Jalankan perkalian skalar pada matrix D dengan hasil dot product pada langkah 4
*hint*: anda dapat menggunakan fungsi `power()`

Secara matematis, langkah di atas dapat dituliskan sebagai berikut.
1. $V = |A - C + (B - D)|$
2. $W = V^{2}$
3. $X = W^{-1}$
4. $Y = X + C$
5. $result = Y*D$

note: untuk perkalian matrix gunakan operasi *

In [12]:
import numpy as np

A = np.array([[7, 8, 5, 3], [2, 9, 4, 6], [3, 7, 1, 8], [5, 2, 6, 4]])
B = np.array([[3, 6, 8, 2], [4, 5, 7, 1], [9, 2, 3, 6], [1, 7, 5, 8]])
C = np.array([[5, 9, 3, 7], [1, 6, 4, 2], [8, 3, 5, 1], [2, 7, 9, 4]])
D = np.array([[6, 3, 5, 8], [2, 7, 9, 4], [1, 8, 6, 2], [5, 4, 3, 7]])

# 1. |A - C + (B - D)|
V = np.abs(A - C + (B - D))

# 2. V^{2}
W = np.power(V, 2)

# 3. W^{-1}
X = np.linalg.pinv(W)

# 4. X + C
Y = X + C

# 5. Y*D (RESULT)
result = Y * D

print("Array:")
print(result)

Array:
[[30.18326693 27.41434263 14.86968792 55.68791501]
 [ 2.00885347 41.83576804 35.9497012   9.02810978]
 [ 7.92297477 23.53253652 30.38346614  2.05544489]
 [10.14386897 28.05666224 26.95351926 27.88224878]]


## Nomor 3

Terdapat sebuah array sebagai berikut.

In [291]:
arr_3 = np.array([ 64, 152, 120, 136, 112,  80,  48,  40, 144,  72,  16,  56,  24, 160,  32, 104,  96,   8,  88, 128])

Untuk setiap elemen arr_3, bagi setiap angka dalam array dengan 8 dan kemudian hitung serta tampilkan rata-rata, median, nilai minimum, standar deviasi, variance, dan percentile 70!

In [5]:
import numpy as np

# Definisikan array
arr_3 = np.array([64, 152, 120, 136, 112, 80, 48, 40, 144, 72, 
                  16, 56, 24, 160, 32, 104, 96, 8, 88, 128])

# Initialize elemen
temp = arr_3 / 8

# Hitung statistik
mean_value = np.mean(temp)
median_value = np.median(temp)
min_value = np.min(temp)
standar_deviasi = np.std(temp)
variance = np.var(temp)
percentile_70 = np.percentile(temp, 70)

# Tampilkan output
print("Mean:", mean_value)
print("Median:", median_value)
print("Minimum:", min_value)
print("Standar Deviasi:", standar_deviasi)
print("Variance:", variance)
print("Percentile ke-70:", percentile_70)


Mean: 10.5
Median: 10.5
Minimum: 1.0
Standar Deviasi: 5.766281297335398
Variance: 33.25
Percentile ke-70: 14.299999999999999


# Sumber Data

* Zoo Data : https://archive.ics.uci.edu/dataset/111/zoo
* Sales Data : https://www.kaggle.com/datasets/emmanueldjegou/sales-dataset-enlarged
* School Nutirtions Program : https://www.kaggle.com/datasets/harshitsrivastava25/school-nutrition-programs